### ISSUE TITLE
Incorrect implementation of pandas interface?

### ISSUE THREAD

**Issue by wisp3rwind** [ContinuumIO/cyberpandas#33]
I am currently looking at this project as a template for implementing the pandas ExtensionArray interface. If I am not mistaken (and I might be, I don't understand the API very well yet), 
https://github.com/ContinuumIO/cyberpandas/blob/c66bbecaf5193bd284a0fddfde65395d119aad41/cyberpandas/base.py#L20
should be in the simplest case
``` python
        return cls(original.take(values))
```
cf. for example `pandas.core.arrays.categorical.Categorical._from_factorized`

**Comment by TomAugspurger** [comment]
Hmm I think you're correct

```python
In [5]: pd.factorize(IPArray([10, 1, 2]))
Out[5]: (array([0, 1, 2]), IPArray(['0.0.0.10', '0.0.0.1', '0.0.0.2']))

In [6]: IPArray._from_factorized(*pd.factorize(IPArray([10, 1, 2])))
Out[6]: IPArray(['0.0.0.0', '0.0.0.1', '0.0.0.2'])
```

vs.

```python
In [7]: values, original = pd.factorize(IPArray([10, 1, 2]))

In [8]: original.take(values)
Out[8]: IPArray(['0.0.0.10', '0.0.0.1', '0.0.0.2'])
```

Any interest in making a PR to fix it?

**Comment by wisp3rwind** [comment]
I can make a PR for this one line, I've checked out the repo anyway. However, I'm not actively interested in cyberpandas as a user right now, so I wouldn't want to invest time into writing tests or otherwise getting to know the codebase better...

**Comment by TomAugspurger** [comment]
No worries. I can take care of it later in the week.

**Comment by wisp3rwind** [comment]
Closed, see https://github.com/pandas-dev/pandas/issues/21343. Sorry for the fuss...
